# databases:
#   - name: office-assets-db
#     plan: free

# services:
#   - type: web
#     name: office-asset-management
#     env: node
#     plan: free
#     buildCommand: npm ci && npm run build
#     startCommand: npm start
#     autoDeploy: true
#     healthCheckPath: /
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: DATABASE_URL
#         fromDatabase:
#           name: office-assets-db
#           property: connectionString
#       - key: JWT_SECRET
#         generateValue: true
#       - key: ADMIN_USERNAME
#         value: admin
#       - key: ADMIN_PASSWORD
#         value: admin123
#       - key: ADMIN_EMAIL
#         value: admin@example.com
#       - key: ADMIN_DEPARTMENT
#         value: IT
#     postDeployCommand: npm run db:push && npm run seed:admin



# Exported from Render on 2025-08-26T12:54:27Z
version: "1"

services:
  - type: web
    name: office-asset-management
    runtime: node
    repo: https://github.com/lenonkay1/office-asset-management-system
    plan: free
    envVars:
      - key: ADMIN_DEPARTMENT
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit

jobs:
  - type: cron
    name: db-migrate-and-seed
    runtime: node
    repo: https://github.com/lenonkay1/office-asset-management-system
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
    schedule: "manual" # won’t run automatically; trigger it when needed
    buildCommand: npm ci
    startCommand: npm run db:push && npm run seed:admin
