databases:
  - name: office-assets-db
    plan: free

services:
  - type: web
    name: office-asset-management
    env: node
    plan: free
    buildCommand: npm ci && npm run build  # Fixed typo: c1 → ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /

# Move postDeployCommand to root level
postDeployCommand: npm run db:push && npm run seed:admin

envVars:
  - key: NODE_ENV  # Fixed: MODE_ENV → NODE_ENV
    value: production
  - key: DATABASE_URL
    fromDatabase:
      name: office-assets-db
      property: connectionString
  - key: JWT_SECRET
    generateValue: true
  - key: ADMIN_USERNAME
    value: admin
  - key: ADMIN_PASSWORD
    value: admin123
  - key: ADMIN_EMAIL
    value: admin@example.com  # Added missing value